create table travel_data_details (
	index int primary key,
	date varchar(12),
	state_fips int,
	state_code varchar(2),
	pop_stay_at_home int,
	pop_not_stay_at_home int,
	trips int,
	trips_1 int,
	trips_1_3 int,
	trips_3_5 int,
	trips_5_10 int,
	trips_10_25 int,
	trips_25_50 int,
	trips_50_100 int,
	trips_100_250 int,
	trips_250_500 int,
	trips_500 int,
	year varchar(4),
	month varchar(2),
	day varchar(2),
	month_abbr varchar(3),
	month_year varchar(10),
	state varchar(30),
	latitude float,
	longitude float
)
